
[reload]
	#Set true if you want to reload guns when ammo is empty by clicking left button
	left_click_reload = true

[kill_message]
	#Set true if you want to show kill message
	show_kill_message = true
	#The max count of kill messages to show concurrently
	#Range: 1 ~ 20
	kill_message_count = 5

[display]
	#Set true if you want to show kill indication while killing an entity
	kill_indication = true
	#Set true to show ammo and gun info on HUD
	ammo_hud = true
	#Set true to enable float cross hair
	float_cross_hair = true
	#Set true to enable camera rotate when holding a gun
	camera_rotate = true
	#Set true to enable armor plate hud
	armor_plate_hud = false
	#Set true to enable stamina hud
	stamina_hud = false
	#The strength of screen shaking while firing with a weapon
	#Range: 0 ~ 100
	weapon_screen_shake = 100
	#The strength of screen shaking while exploding
	#Range: 0 ~ 100
	explosion_screen_shake = 100
	#The strength of screen shaking when shocked
	#Range: 0 ~ 100
	shock_screen_shake = 100

[invert_aircraft_control]
	#Set true to invert aircraft control
	invert_aircraft_control = false

[checksum]
	#System environment checksum, do not edit
	environment_checksum = ""

